name: Main Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: divyatrm/pipeline/.github/workflows/main.yml@main
