name: Monitor Repository
on:
  push:
    branches:
      - master
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test code
        uses: divyatrm/pipeline/.github/workflows/main.yml@main
